import { CurriculumLine } from "./types";

export const CURRICULUM_LINES: CurriculumLine[] = [
  {
    id: "fe-line",
    title: "フロントエンドライン",
    summary: "UI/UXを実装できるようになる",
    units: [
      { id: "fe-1", title: "HTML/CSS基礎", description: "レイアウト・レスポンシブ・フォーム" },
      { id: "fe-2", title: "JavaScript基礎", description: "DOM操作・イベント・非同期" },
      { id: "fe-3", title: "React基礎", description: "コンポーネント・Hooks基本" },
      { id: "fe-4", title: "状態管理・API連携", description: "Zustand/Queryなど" },
      { id: "fe-5", title: "UI/UX・a11y", description: "フォーム設計・アクセシビリティ" },
      { id: "fe-6", title: "テスト・パフォーマンス", description: "Unit/E2E・メモ化" },
    ],
    missions: ["学習ダッシュボード実装", "学習ロググラフ表示"],
    missionDetails: [
      {
        id: "fe-m1",
        title: "学習ダッシュボードUIを作る",
        description: "カードレイアウトで学習時間と進捗を表示し、レスポンシブ対応する。",
        expectedOutputs: ["カード/グラフコンポーネント", "レスポンシブCSS", "ダミーデータ表示"],
        tools: ["React", "Next.js", "Tailwind"],
        tags: ["dashboard", "responsive"],
        effortMinutes: 180,
      },
      {
        id: "fe-m2",
        title: "学習ロググラフ表示",
        description: "API（mock可）から取得した学習時間を週次グラフで可視化する。",
        expectedOutputs: ["棒グラフ/折れ線グラフ", "ローディング/エラー表示"],
        tools: ["React", "Chartライブラリ"],
        tags: ["data-viz", "api"],
        effortMinutes: 120,
      },
    ],
  },
  {
    id: "be-line",
    title: "バックエンドライン",
    summary: "APIとデータを設計・提供する",
    units: [
      { id: "be-1", title: "HTTP/REST概念" },
      { id: "be-2", title: "フレームワーク入門" },
      { id: "be-3", title: "DB設計・SQL" },
      { id: "be-4", title: "認証・認可" },
      { id: "be-5", title: "エラー/ログ設計" },
      { id: "be-6", title: "レイヤード設計" },
    ],
    missions: ["学習ログAPI実装", "ミッションCRUD実装"],
    missionDetails: [
      {
        id: "be-m1",
        title: "学習ログAPIを設計・実装",
        description: "RESTで学習セッションを登録/一覧/更新できるAPIを作る。",
        expectedOutputs: ["OpenAPI/YAML", "CRUDエンドポイント", "バリデーション/認証"],
        tools: ["Node/Express or Next Route Handler", "Prisma"],
        tags: ["api", "crud", "auth"],
        effortMinutes: 180,
      },
      {
        id: "be-m2",
        title: "ミッションCRUD + 評価サマリー",
        description: "ミッション（実務ごっこ）のCRUDと、評価サマリー取得APIを実装。",
        expectedOutputs: ["CRUD", "集計クエリ", "テストコード(任意)"],
        tools: ["Node/Express or Next Route Handler", "Prisma"],
        tags: ["mission", "aggregation"],
        effortMinutes: 180,
      },
    ],
  },
  {
    id: "infra-line",
    title: "インフラ/クラウドライン",
    summary: "安全に届け続ける基礎を学ぶ",
    units: [
      { id: "inf-1", title: "サーバ/OS/プロセス" },
      { id: "inf-2", title: "ネットワーク基礎" },
      { id: "inf-3", title: "クラウド入門" },
      { id: "inf-4", title: "デプロイ実践" },
      { id: "inf-5", title: "監視・ログ" },
      { id: "inf-6", title: "セキュリティ超入門" },
    ],
    missions: ["テスト環境立ち上げ", "障害原因の整理ワーク"],
    missionDetails: [
      {
        id: "inf-m1",
        title: "テスト環境を立ち上げる",
        description: "Next.jsアプリをテスト環境へデプロイし、動作確認フローを文書化。",
        expectedOutputs: ["デプロイ手順", "動作確認チェックリスト", "簡易モニタリング設定"],
        tools: ["Vercel/AWS/GCP", "ログ/モニタリングサービス"],
        tags: ["deploy", "monitoring"],
        effortMinutes: 150,
      },
      {
        id: "inf-m2",
        title: "障害対応シナリオ",
        description: "障害想定のタイムラインを作成し、原因候補と調査手順を整理する。",
        expectedOutputs: ["インシデントメモ", "原因候補リスト", "調査コマンド例"],
        tools: ["Doc/Notion等"],
        tags: ["incident", "postmortem"],
        effortMinutes: 120,
      },
    ],
  },
  {
    id: "fullstack-line",
    title: "フルスタック・連携",
    summary: "小さなプロダクトを一気通貫でつくる",
    units: [{ id: "fs-1", title: "設計〜実装〜デプロイ一気通貫" }],
    missions: ["学習ログアプリを設計・実装・デプロイ"],
    missionDetails: [
      {
        id: "fs-m1",
        title: "学習ログアプリ一気通貫",
        description: "フロント・API・DB・デプロイまで一通り行う小規模プロダクトを仕上げる。",
        expectedOutputs: ["要件メモ", "UIモック", "API/DBスキーマ", "デプロイURL"],
        tools: ["Next.js", "Prisma", "PostgreSQL", "Vercel"],
        tags: ["fullstack", "deploy"],
        effortMinutes: 240,
      },
    ],
  },
  {
    id: "thinking-line",
    title: "思考スキルライン",
    summary: "調べる・メモる・仮説を立てる・論理で説明する力を鍛える",
    units: [
      { id: "rl-1", title: "検索の基礎", description: "キーワード分解 / AND / OR / 検索結果の見方" },
      { id: "rl-2", title: "情報の信頼性", description: "一次情報・広告判定・ソースの見極め" },
      { id: "nt-1", title: "メモの3モード", description: "ブレインダンプ/箇条書き/図解" },
      { id: "nt-2", title: "5W2Hメモ", description: "枠を使って整理する" },
      { id: "ht-1", title: "仮説の立て方", description: "仮説を複数出して小さく試す" },
      { id: "lg-1", title: "ロジックツリー", description: "MECEで分解する" },
      { id: "ct-1", title: "批判的思考", description: "主張・根拠・前提を分けて確認する" },
    ],
    missions: ["検索とAI比較で調べる", "5W2Hでメモ→AIにチェックしてもらう"],
    missionDetails: [
      {
        id: "think-m1",
        title: "検索 × AI 比較メモ",
        description: "同じテーマを検索とAIで調べ、共通点/違い/怪しさをメモにまとめる。",
        expectedOutputs: ["共通点3つ", "違い3つ", "怪しいポイント2つ"],
        tools: ["検索エンジン", "AIチャット"],
        tags: ["RESEARCH_KEYWORDING", "RESEARCH_AI_POSITIONING"],
        effortMinutes: 45,
      },
      {
        id: "think-m2",
        title: "5W2Hメモ→AIに抜け確認",
        description: "5W2Hでメモを作り、AIに足りない視点を指摘してもらう。",
        expectedOutputs: ["5W2Hメモ", "AIからの補足ポイント"],
        tools: ["メモツール", "AIチャット"],
        tags: ["NOTE_5W2H", "STRUCTURING"],
        effortMinutes: 30,
      },
      {
        id: "think-m3",
        title: "仮説ログづくり",
        description: "仮説5本→AIに反証してもらい、結果と学びを記録する。",
        expectedOutputs: ["仮説5本", "反証/学びメモ"],
        tools: ["メモツール", "AIチャット"],
        tags: ["HYPOTHESIS_GENERATION", "HYPOTHESIS_TESTING", "HYPOTHESIS_LOGGING"],
        effortMinutes: 40,
      },
    ],
  },
];
